name: Docker Commit

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  distroless:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'
    name: Tag Distroless Commit (node:${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: quay.io/soketi/k8soketi
          tags: |
            type=ref,event=pr,suffix=-${{ matrix.node }}-distroless
          labels: |
            quay.expires-after=7d
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.distroless
          build-args: |
            VERSION=${{ matrix.node }}
          cache-from: |
            type=gha,scope=distroless
          cache-to: |
            type=gha,scope=distroless
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
  debian:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'
    name: Tag Debian Commit (node:${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: quay.io/soketi/k8soketi
          tags: |
            type=ref,event=pr,suffix=-${{ matrix.node }}-debian
          labels: |
            quay.expires-after=7d
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile.debian
          build-args: |
            VERSION=${{ matrix.node }}
          cache-from: |
            type=gha,scope=debian
          cache-to: |
            type=gha,scope=debian
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
