name: Docker Commit

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    tags-ignore:
      - "*"

jobs:
  distroless:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'
    name: Tag Distroless Commit (node:${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: quay.io/soketi/k8soketi:${{ github.sha }}-${{ matrix.node }}-distroless
          file: Dockerfile.distroless
          build-args: |
            VERSION=${{ matrix.node }}
  debian:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - '18'
    name: Tag Debian Commit (node:${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: quay.io/soketi/k8soketi:${{ github.sha }}-${{ matrix.node }}-debian
          file: Dockerfile.debian
          build-args: |
            VERSION=${{ matrix.node }}
