name: Docker Latest - Standard

on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    tags-ignore:
      - "*"
    branches-ignore:
      - "*"

jobs:
  distroless:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '18'
    name: Tag Latest Distroless (node:${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: quay.io/soketi/k8soketi:latest-${{ matrix.node }}-distroless
          file: Dockerfile.distroless
          build-args: |
            VERSION=${{ matrix.node }}
          platforms: |
            linux/amd64
            linux/arm64
  debian:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - '18'
    name: Tag Latest Debian (node:${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: quay.io/soketi/k8soketi:latest-${{ matrix.node }}-debian
          file: Dockerfile.debian
          build-args: |
            VERSION=${{ matrix.node }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7
